/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status from './Status';

/**
 * The ArbitratorStatus model module.
 * @module model/ArbitratorStatus
 * @version 3.12.9
 */
class ArbitratorStatus {
    /**
     * Constructs a new <code>ArbitratorStatus</code>.
     * @alias module:model/ArbitratorStatus
     * @param url {String} 
     * @param status {module:model/Status} 
     */
    constructor(url, status) { 
        
        ArbitratorStatus.initialize(this, url, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, status) { 
        obj['url'] = url;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ArbitratorStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArbitratorStatus} obj Optional instance to populate.
     * @return {module:model/ArbitratorStatus} The populated <code>ArbitratorStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArbitratorStatus();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArbitratorStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArbitratorStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArbitratorStatus.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

ArbitratorStatus.RequiredProperties = ["url", "status"];

/**
 * @member {String} url
 */
ArbitratorStatus.prototype['url'] = undefined;

/**
 * @member {module:model/Status} status
 */
ArbitratorStatus.prototype['status'] = undefined;






export default ArbitratorStatus;

