/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DaemonSubsystemAlert model module.
 * @module model/DaemonSubsystemAlert
 * @version 3.12.19
 */
class DaemonSubsystemAlert {
    /**
     * Constructs a new <code>DaemonSubsystemAlert</code>.
     * @alias module:model/DaemonSubsystemAlert
     * @param message {String} 
     * @param severity {String} 
     */
    constructor(message, severity) { 
        
        DaemonSubsystemAlert.initialize(this, message, severity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, severity) { 
        obj['message'] = message;
        obj['severity'] = severity;
    }

    /**
     * Constructs a <code>DaemonSubsystemAlert</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DaemonSubsystemAlert} obj Optional instance to populate.
     * @return {module:model/DaemonSubsystemAlert} The populated <code>DaemonSubsystemAlert</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DaemonSubsystemAlert();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DaemonSubsystemAlert</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DaemonSubsystemAlert</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DaemonSubsystemAlert.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['severity'] && !(typeof data['severity'] === 'string' || data['severity'] instanceof String)) {
            throw new Error("Expected the field `severity` to be a primitive type in the JSON string but got " + data['severity']);
        }

        return true;
    }


}

DaemonSubsystemAlert.RequiredProperties = ["message", "severity"];

/**
 * @member {String} message
 */
DaemonSubsystemAlert.prototype['message'] = undefined;

/**
 * @member {String} severity
 */
DaemonSubsystemAlert.prototype['severity'] = undefined;






export default DaemonSubsystemAlert;

