/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceMonitor from './ResourceMonitor';

/**
 * The InstanceMonitor model module.
 * @module model/InstanceMonitor
 * @version 3.12.2
 */
class InstanceMonitor {
    /**
     * Constructs a new <code>InstanceMonitor</code>.
     * @alias module:model/InstanceMonitor
     * @param globalExpect {String} 
     * @param globalExpectUpdatedAt {Date} 
     * @param globalExpectOptions {Object} 
     * @param isLeader {Boolean} 
     * @param isHaLeader {Boolean} 
     * @param localExpect {String} 
     * @param localExpectUpdatedAt {Date} 
     * @param orchestrationId {String} 
     * @param orchestrationIsDone {Boolean} 
     * @param sessionId {String} 
     * @param state {String} 
     * @param stateUpdatedAt {Date} 
     * @param monitorActionExecutedAt {Date} 
     * @param isPreserved {Boolean} 
     * @param resources {Object.<String, module:model/ResourceMonitor>} 
     * @param updatedAt {Date} 
     * @param parents {Object} 
     * @param children {Object} 
     */
    constructor(globalExpect, globalExpectUpdatedAt, globalExpectOptions, isLeader, isHaLeader, localExpect, localExpectUpdatedAt, orchestrationId, orchestrationIsDone, sessionId, state, stateUpdatedAt, monitorActionExecutedAt, isPreserved, resources, updatedAt, parents, children) { 
        
        InstanceMonitor.initialize(this, globalExpect, globalExpectUpdatedAt, globalExpectOptions, isLeader, isHaLeader, localExpect, localExpectUpdatedAt, orchestrationId, orchestrationIsDone, sessionId, state, stateUpdatedAt, monitorActionExecutedAt, isPreserved, resources, updatedAt, parents, children);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, globalExpect, globalExpectUpdatedAt, globalExpectOptions, isLeader, isHaLeader, localExpect, localExpectUpdatedAt, orchestrationId, orchestrationIsDone, sessionId, state, stateUpdatedAt, monitorActionExecutedAt, isPreserved, resources, updatedAt, parents, children) { 
        obj['global_expect'] = globalExpect;
        obj['global_expect_updated_at'] = globalExpectUpdatedAt;
        obj['global_expect_options'] = globalExpectOptions;
        obj['is_leader'] = isLeader;
        obj['is_ha_leader'] = isHaLeader;
        obj['local_expect'] = localExpect;
        obj['local_expect_updated_at'] = localExpectUpdatedAt;
        obj['orchestration_id'] = orchestrationId;
        obj['orchestration_is_done'] = orchestrationIsDone;
        obj['session_id'] = sessionId;
        obj['state'] = state;
        obj['state_updated_at'] = stateUpdatedAt;
        obj['monitor_action_executed_at'] = monitorActionExecutedAt;
        obj['is_preserved'] = isPreserved;
        obj['resources'] = resources;
        obj['updated_at'] = updatedAt;
        obj['parents'] = parents;
        obj['children'] = children;
    }

    /**
     * Constructs a <code>InstanceMonitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceMonitor} obj Optional instance to populate.
     * @return {module:model/InstanceMonitor} The populated <code>InstanceMonitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceMonitor();

            if (data.hasOwnProperty('global_expect')) {
                obj['global_expect'] = ApiClient.convertToType(data['global_expect'], 'String');
            }
            if (data.hasOwnProperty('global_expect_updated_at')) {
                obj['global_expect_updated_at'] = ApiClient.convertToType(data['global_expect_updated_at'], 'Date');
            }
            if (data.hasOwnProperty('global_expect_options')) {
                obj['global_expect_options'] = ApiClient.convertToType(data['global_expect_options'], Object);
            }
            if (data.hasOwnProperty('is_leader')) {
                obj['is_leader'] = ApiClient.convertToType(data['is_leader'], 'Boolean');
            }
            if (data.hasOwnProperty('is_ha_leader')) {
                obj['is_ha_leader'] = ApiClient.convertToType(data['is_ha_leader'], 'Boolean');
            }
            if (data.hasOwnProperty('local_expect')) {
                obj['local_expect'] = ApiClient.convertToType(data['local_expect'], 'String');
            }
            if (data.hasOwnProperty('local_expect_updated_at')) {
                obj['local_expect_updated_at'] = ApiClient.convertToType(data['local_expect_updated_at'], 'Date');
            }
            if (data.hasOwnProperty('orchestration_id')) {
                obj['orchestration_id'] = ApiClient.convertToType(data['orchestration_id'], 'String');
            }
            if (data.hasOwnProperty('orchestration_is_done')) {
                obj['orchestration_is_done'] = ApiClient.convertToType(data['orchestration_is_done'], 'Boolean');
            }
            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('state_updated_at')) {
                obj['state_updated_at'] = ApiClient.convertToType(data['state_updated_at'], 'Date');
            }
            if (data.hasOwnProperty('monitor_action_executed_at')) {
                obj['monitor_action_executed_at'] = ApiClient.convertToType(data['monitor_action_executed_at'], 'Date');
            }
            if (data.hasOwnProperty('is_preserved')) {
                obj['is_preserved'] = ApiClient.convertToType(data['is_preserved'], 'Boolean');
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], {'String': ResourceMonitor});
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('parents')) {
                obj['parents'] = ApiClient.convertToType(data['parents'], Object);
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstanceMonitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstanceMonitor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InstanceMonitor.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['global_expect'] && !(typeof data['global_expect'] === 'string' || data['global_expect'] instanceof String)) {
            throw new Error("Expected the field `global_expect` to be a primitive type in the JSON string but got " + data['global_expect']);
        }
        // ensure the json data is a string
        if (data['local_expect'] && !(typeof data['local_expect'] === 'string' || data['local_expect'] instanceof String)) {
            throw new Error("Expected the field `local_expect` to be a primitive type in the JSON string but got " + data['local_expect']);
        }
        // ensure the json data is a string
        if (data['orchestration_id'] && !(typeof data['orchestration_id'] === 'string' || data['orchestration_id'] instanceof String)) {
            throw new Error("Expected the field `orchestration_id` to be a primitive type in the JSON string but got " + data['orchestration_id']);
        }
        // ensure the json data is a string
        if (data['session_id'] && !(typeof data['session_id'] === 'string' || data['session_id'] instanceof String)) {
            throw new Error("Expected the field `session_id` to be a primitive type in the JSON string but got " + data['session_id']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}

InstanceMonitor.RequiredProperties = ["global_expect", "global_expect_updated_at", "global_expect_options", "is_leader", "is_ha_leader", "local_expect", "local_expect_updated_at", "orchestration_id", "orchestration_is_done", "session_id", "state", "state_updated_at", "monitor_action_executed_at", "is_preserved", "resources", "updated_at", "parents", "children"];

/**
 * @member {String} global_expect
 */
InstanceMonitor.prototype['global_expect'] = undefined;

/**
 * @member {Date} global_expect_updated_at
 */
InstanceMonitor.prototype['global_expect_updated_at'] = undefined;

/**
 * @member {Object} global_expect_options
 */
InstanceMonitor.prototype['global_expect_options'] = undefined;

/**
 * @member {Boolean} is_leader
 */
InstanceMonitor.prototype['is_leader'] = undefined;

/**
 * @member {Boolean} is_ha_leader
 */
InstanceMonitor.prototype['is_ha_leader'] = undefined;

/**
 * @member {String} local_expect
 */
InstanceMonitor.prototype['local_expect'] = undefined;

/**
 * @member {Date} local_expect_updated_at
 */
InstanceMonitor.prototype['local_expect_updated_at'] = undefined;

/**
 * @member {String} orchestration_id
 */
InstanceMonitor.prototype['orchestration_id'] = undefined;

/**
 * @member {Boolean} orchestration_is_done
 */
InstanceMonitor.prototype['orchestration_is_done'] = undefined;

/**
 * @member {String} session_id
 */
InstanceMonitor.prototype['session_id'] = undefined;

/**
 * @member {String} state
 */
InstanceMonitor.prototype['state'] = undefined;

/**
 * @member {Date} state_updated_at
 */
InstanceMonitor.prototype['state_updated_at'] = undefined;

/**
 * @member {Date} monitor_action_executed_at
 */
InstanceMonitor.prototype['monitor_action_executed_at'] = undefined;

/**
 * @member {Boolean} is_preserved
 */
InstanceMonitor.prototype['is_preserved'] = undefined;

/**
 * @member {Object.<String, module:model/ResourceMonitor>} resources
 */
InstanceMonitor.prototype['resources'] = undefined;

/**
 * @member {Date} updated_at
 */
InstanceMonitor.prototype['updated_at'] = undefined;

/**
 * @member {Object} parents
 */
InstanceMonitor.prototype['parents'] = undefined;

/**
 * @member {Object} children
 */
InstanceMonitor.prototype['children'] = undefined;






export default InstanceMonitor;

