/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Kind.
* @enum {}
* @readonly
*/
export default class Kind {
    
        /**
         * value: "svc"
         * @const
         */
        "svc" = "svc";

    
        /**
         * value: "vol"
         * @const
         */
        "vol" = "vol";

    
        /**
         * value: "cfg"
         * @const
         */
        "cfg" = "cfg";

    
        /**
         * value: "sec"
         * @const
         */
        "sec" = "sec";

    
        /**
         * value: "usr"
         * @const
         */
        "usr" = "usr";

    
        /**
         * value: "nscfg"
         * @const
         */
        "nscfg" = "nscfg";

    
        /**
         * value: "ccfg"
         * @const
         */
        "ccfg" = "ccfg";

    

    /**
    * Returns a <code>Kind</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Kind} The enum <code>Kind</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

