/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NodeActionAccepted model module.
 * @module model/NodeActionAccepted
 * @version 3.12.19
 */
class NodeActionAccepted {
    /**
     * Constructs a new <code>NodeActionAccepted</code>.
     * @alias module:model/NodeActionAccepted
     * @param sessionId {String} 
     */
    constructor(sessionId) { 
        
        NodeActionAccepted.initialize(this, sessionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sessionId) { 
        obj['session_id'] = sessionId;
    }

    /**
     * Constructs a <code>NodeActionAccepted</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NodeActionAccepted} obj Optional instance to populate.
     * @return {module:model/NodeActionAccepted} The populated <code>NodeActionAccepted</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeActionAccepted();

            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NodeActionAccepted</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NodeActionAccepted</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NodeActionAccepted.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['session_id'] && !(typeof data['session_id'] === 'string' || data['session_id'] instanceof String)) {
            throw new Error("Expected the field `session_id` to be a primitive type in the JSON string but got " + data['session_id']);
        }

        return true;
    }


}

NodeActionAccepted.RequiredProperties = ["session_id"];

/**
 * @member {String} session_id
 */
NodeActionAccepted.prototype['session_id'] = undefined;






export default NodeActionAccepted;

