/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PlacementPolicy.
* @enum {}
* @readonly
*/
export default class PlacementPolicy {
    
        /**
         * value: "last start"
         * @const
         */
        "last start" = "last start";

    
        /**
         * value: "load avg"
         * @const
         */
        "load avg" = "load avg";

    
        /**
         * value: "nodes order"
         * @const
         */
        "nodes order" = "nodes order";

    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "score"
         * @const
         */
        "score" = "score";

    
        /**
         * value: "spread"
         * @const
         */
        "spread" = "spread";

    
        /**
         * value: "shift"
         * @const
         */
        "shift" = "shift";

    

    /**
    * Returns a <code>PlacementPolicy</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PlacementPolicy} The enum <code>PlacementPolicy</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

