/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PlacementState.
* @enum {}
* @readonly
*/
export default class PlacementState {
    
        /**
         * value: "optimal"
         * @const
         */
        "optimal" = "optimal";

    
        /**
         * value: "non-optimal"
         * @const
         */
        "non-optimal" = "non-optimal";

    
        /**
         * value: "n/a"
         * @const
         */
        "n/a" = "n/a";

    
        /**
         * value: "undef"
         * @const
         */
        "undef" = "undef";

    

    /**
    * Returns a <code>PlacementState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PlacementState} The enum <code>PlacementState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

