/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostNodeDRBDConfigRequest model module.
 * @module model/PostNodeDRBDConfigRequest
 * @version 3.12.2
 */
class PostNodeDRBDConfigRequest {
    /**
     * Constructs a new <code>PostNodeDRBDConfigRequest</code>.
     * @alias module:model/PostNodeDRBDConfigRequest
     * @param allocationId {String} 
     * @param data {Blob} 
     */
    constructor(allocationId, data) { 
        
        PostNodeDRBDConfigRequest.initialize(this, allocationId, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, allocationId, data) { 
        obj['allocation_id'] = allocationId;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>PostNodeDRBDConfigRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostNodeDRBDConfigRequest} obj Optional instance to populate.
     * @return {module:model/PostNodeDRBDConfigRequest} The populated <code>PostNodeDRBDConfigRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostNodeDRBDConfigRequest();

            if (data.hasOwnProperty('allocation_id')) {
                obj['allocation_id'] = ApiClient.convertToType(data['allocation_id'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostNodeDRBDConfigRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostNodeDRBDConfigRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostNodeDRBDConfigRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['allocation_id'] && !(typeof data['allocation_id'] === 'string' || data['allocation_id'] instanceof String)) {
            throw new Error("Expected the field `allocation_id` to be a primitive type in the JSON string but got " + data['allocation_id']);
        }

        return true;
    }


}

PostNodeDRBDConfigRequest.RequiredProperties = ["allocation_id", "data"];

/**
 * @member {String} allocation_id
 */
PostNodeDRBDConfigRequest.prototype['allocation_id'] = undefined;

/**
 * @member {Blob} data
 */
PostNodeDRBDConfigRequest.prototype['data'] = undefined;






export default PostNodeDRBDConfigRequest;

