/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostObjectActionSwitch model module.
 * @module model/PostObjectActionSwitch
 * @version 3.12.2
 */
class PostObjectActionSwitch {
    /**
     * Constructs a new <code>PostObjectActionSwitch</code>.
     * @alias module:model/PostObjectActionSwitch
     * @param destination {Array.<String>} 
     */
    constructor(destination) { 
        
        PostObjectActionSwitch.initialize(this, destination);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, destination) { 
        obj['destination'] = destination;
    }

    /**
     * Constructs a <code>PostObjectActionSwitch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostObjectActionSwitch} obj Optional instance to populate.
     * @return {module:model/PostObjectActionSwitch} The populated <code>PostObjectActionSwitch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostObjectActionSwitch();

            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostObjectActionSwitch</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostObjectActionSwitch</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostObjectActionSwitch.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['destination'])) {
            throw new Error("Expected the field `destination` to be an array in the JSON data but got " + data['destination']);
        }

        return true;
    }


}

PostObjectActionSwitch.RequiredProperties = ["destination"];

/**
 * @member {Array.<String>} destination
 */
PostObjectActionSwitch.prototype['destination'] = undefined;






export default PostObjectActionSwitch;

