/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Problem model module.
 * @module model/Problem
 * @version 3.12.19
 */
class Problem {
    /**
     * Constructs a new <code>Problem</code>.
     * @alias module:model/Problem
     * @param detail {String} A human-readable explanation specific to this occurrence of the problem. 
     * @param status {Number} The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. 
     * @param title {String} A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4). 
     */
    constructor(detail, status, title) { 
        
        Problem.initialize(this, detail, status, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, detail, status, title) { 
        obj['detail'] = detail;
        obj['status'] = status;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>Problem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Problem} obj Optional instance to populate.
     * @return {module:model/Problem} The populated <code>Problem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Problem();

            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Problem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Problem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Problem.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['detail'] && !(typeof data['detail'] === 'string' || data['detail'] instanceof String)) {
            throw new Error("Expected the field `detail` to be a primitive type in the JSON string but got " + data['detail']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

Problem.RequiredProperties = ["detail", "status", "title"];

/**
 * A human-readable explanation specific to this occurrence of the problem. 
 * @member {String} detail
 */
Problem.prototype['detail'] = undefined;

/**
 * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. 
 * @member {Number} status
 */
Problem.prototype['status'] = undefined;

/**
 * A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4). 
 * @member {String} title
 */
Problem.prototype['title'] = undefined;






export default Problem;

