/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResourceConfig model module.
 * @module model/ResourceConfig
 * @version 3.12.2
 */
class ResourceConfig {
    /**
     * Constructs a new <code>ResourceConfig</code>.
     * @alias module:model/ResourceConfig
     * @param isDisabled {Boolean} 
     * @param isMonitored {Boolean} 
     * @param isStandby {Boolean} 
     * @param restart {Number} 
     * @param restartDelay {String} 
     */
    constructor(isDisabled, isMonitored, isStandby, restart, restartDelay) { 
        
        ResourceConfig.initialize(this, isDisabled, isMonitored, isStandby, restart, restartDelay);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isDisabled, isMonitored, isStandby, restart, restartDelay) { 
        obj['is_disabled'] = isDisabled;
        obj['is_monitored'] = isMonitored;
        obj['is_standby'] = isStandby;
        obj['restart'] = restart;
        obj['restart_delay'] = restartDelay;
    }

    /**
     * Constructs a <code>ResourceConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourceConfig} obj Optional instance to populate.
     * @return {module:model/ResourceConfig} The populated <code>ResourceConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceConfig();

            if (data.hasOwnProperty('is_disabled')) {
                obj['is_disabled'] = ApiClient.convertToType(data['is_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_monitored')) {
                obj['is_monitored'] = ApiClient.convertToType(data['is_monitored'], 'Boolean');
            }
            if (data.hasOwnProperty('is_standby')) {
                obj['is_standby'] = ApiClient.convertToType(data['is_standby'], 'Boolean');
            }
            if (data.hasOwnProperty('restart')) {
                obj['restart'] = ApiClient.convertToType(data['restart'], 'Number');
            }
            if (data.hasOwnProperty('restart_delay')) {
                obj['restart_delay'] = ApiClient.convertToType(data['restart_delay'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ResourceConfig.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['restart_delay'] && !(typeof data['restart_delay'] === 'string' || data['restart_delay'] instanceof String)) {
            throw new Error("Expected the field `restart_delay` to be a primitive type in the JSON string but got " + data['restart_delay']);
        }

        return true;
    }


}

ResourceConfig.RequiredProperties = ["is_disabled", "is_monitored", "is_standby", "restart", "restart_delay"];

/**
 * @member {Boolean} is_disabled
 */
ResourceConfig.prototype['is_disabled'] = undefined;

/**
 * @member {Boolean} is_monitored
 */
ResourceConfig.prototype['is_monitored'] = undefined;

/**
 * @member {Boolean} is_standby
 */
ResourceConfig.prototype['is_standby'] = undefined;

/**
 * @member {Number} restart
 */
ResourceConfig.prototype['restart'] = undefined;

/**
 * @member {String} restart_delay
 */
ResourceConfig.prototype['restart_delay'] = undefined;






export default ResourceConfig;

