/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Resource from './Resource';
import ResourceMeta from './ResourceMeta';

/**
 * The ResourceItem model module.
 * @module model/ResourceItem
 * @version 3.12.2
 */
class ResourceItem {
    /**
     * Constructs a new <code>ResourceItem</code>.
     * @alias module:model/ResourceItem
     * @param kind {module:model/ResourceItem.KindEnum} 
     * @param meta {module:model/ResourceMeta} 
     * @param data {module:model/Resource} 
     */
    constructor(kind, meta, data) { 
        
        ResourceItem.initialize(this, kind, meta, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind, meta, data) { 
        obj['kind'] = kind;
        obj['meta'] = meta;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ResourceItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourceItem} obj Optional instance to populate.
     * @return {module:model/ResourceItem} The populated <code>ResourceItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceItem();

            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ResourceMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Resource.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ResourceItem.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          ResourceMeta.validateJSON(data['meta']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          Resource.validateJSON(data['data']);
        }

        return true;
    }


}

ResourceItem.RequiredProperties = ["kind", "meta", "data"];

/**
 * @member {module:model/ResourceItem.KindEnum} kind
 */
ResourceItem.prototype['kind'] = undefined;

/**
 * @member {module:model/ResourceMeta} meta
 */
ResourceItem.prototype['meta'] = undefined;

/**
 * @member {module:model/Resource} data
 */
ResourceItem.prototype['data'] = undefined;





/**
 * Allowed values for the <code>kind</code> property.
 * @enum {String}
 * @readonly
 */
ResourceItem['KindEnum'] = {

    /**
     * value: "ResourceItem"
     * @const
     */
    "ResourceItem": "ResourceItem"
};



export default ResourceItem;

