/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceConfig from './ResourceConfig';
import ResourceMonitor from './ResourceMonitor';
import ResourceStatus from './ResourceStatus';

/**
 * The Resource model module.
 * @module model/Resource
 * @version 3.12.9
 */
class Resource {
    /**
     * Constructs a new <code>Resource</code>.
     * @alias module:model/Resource
     */
    constructor() { 
        
        Resource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Resource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Resource} obj Optional instance to populate.
     * @return {module:model/Resource} The populated <code>Resource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Resource();

            if (data.hasOwnProperty('config')) {
                obj['config'] = ResourceConfig.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('monitor')) {
                obj['monitor'] = ResourceMonitor.constructFromObject(data['monitor']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ResourceStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Resource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Resource</code>.
     */
    static validateJSON(data) {
        // validate the optional field `config`
        if (data['config']) { // data not null
          ResourceConfig.validateJSON(data['config']);
        }
        // validate the optional field `monitor`
        if (data['monitor']) { // data not null
          ResourceMonitor.validateJSON(data['monitor']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          ResourceStatus.validateJSON(data['status']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResourceConfig} config
 */
Resource.prototype['config'] = undefined;

/**
 * @member {module:model/ResourceMonitor} monitor
 */
Resource.prototype['monitor'] = undefined;

/**
 * @member {module:model/ResourceStatus} status
 */
Resource.prototype['status'] = undefined;






export default Resource;

