/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResourceMonitorRestart model module.
 * @module model/ResourceMonitorRestart
 * @version 3.12.19
 */
class ResourceMonitorRestart {
    /**
     * Constructs a new <code>ResourceMonitorRestart</code>.
     * @alias module:model/ResourceMonitorRestart
     * @param remaining {Number} 
     * @param lastAt {Date} 
     */
    constructor(remaining, lastAt) { 
        
        ResourceMonitorRestart.initialize(this, remaining, lastAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, remaining, lastAt) { 
        obj['remaining'] = remaining;
        obj['last_at'] = lastAt;
    }

    /**
     * Constructs a <code>ResourceMonitorRestart</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourceMonitorRestart} obj Optional instance to populate.
     * @return {module:model/ResourceMonitorRestart} The populated <code>ResourceMonitorRestart</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceMonitorRestart();

            if (data.hasOwnProperty('remaining')) {
                obj['remaining'] = ApiClient.convertToType(data['remaining'], 'Number');
            }
            if (data.hasOwnProperty('last_at')) {
                obj['last_at'] = ApiClient.convertToType(data['last_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceMonitorRestart</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceMonitorRestart</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ResourceMonitorRestart.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ResourceMonitorRestart.RequiredProperties = ["remaining", "last_at"];

/**
 * @member {Number} remaining
 */
ResourceMonitorRestart.prototype['remaining'] = undefined;

/**
 * @member {Date} last_at
 */
ResourceMonitorRestart.prototype['last_at'] = undefined;






export default ResourceMonitorRestart;

