/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status.
* @enum {}
* @readonly
*/
export default class Status {
    
        /**
         * value: "up"
         * @const
         */
        "up" = "up";

    
        /**
         * value: "down"
         * @const
         */
        "down" = "down";

    
        /**
         * value: "warn"
         * @const
         */
        "warn" = "warn";

    
        /**
         * value: "n/a"
         * @const
         */
        "n/a" = "n/a";

    
        /**
         * value: "undef"
         * @const
         */
        "undef" = "undef";

    
        /**
         * value: "stdby up"
         * @const
         */
        "stdby up" = "stdby up";

    
        /**
         * value: "stdby down"
         * @const
         */
        "stdby down" = "stdby down";

    

    /**
    * Returns a <code>Status</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Status} The enum <code>Status</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

