/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DNSRecord from '../model/DNSRecord';
import Problem from '../model/Problem';

/**
* Dns service.
* @module api/DnsApi
* @version 3.12.9
*/
export default class DnsApi {

    /**
    * Constructs a new DnsApi. 
    * @alias module:api/DnsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getDNSDump operation.
     * @callback module:api/DnsApi~getDNSDumpCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DNSRecord>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Dump the cluster DNS zone contenllt. 
     * @param {module:api/DnsApi~getDNSDumpCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DNSRecord>}
     */
    getDNSDump(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [DNSRecord];
      return this.apiClient.callApi(
        '/dns/dump', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
