/**
 * opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpensvcAgentApi);
  }
}(this, function(expect, OpensvcAgentApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpensvcAgentApi.NodeConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NodeConfig', function() {
    it('should create an instance of NodeConfig', function() {
      // uncomment below and update the code to test NodeConfig
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be.a(OpensvcAgentApi.NodeConfig);
    });

    it('should have the property env (base name: "env")', function() {
      // uncomment below and update the code to test the property env
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be();
    });

    it('should have the property maintenanceGracePeriod (base name: "maintenance_grace_period")', function() {
      // uncomment below and update the code to test the property maintenanceGracePeriod
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be();
    });

    it('should have the property readyPeriod (base name: "ready_period")', function() {
      // uncomment below and update the code to test the property readyPeriod
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be();
    });

    it('should have the property rejoinGracePeriod (base name: "rejoin_grace_period")', function() {
      // uncomment below and update the code to test the property rejoinGracePeriod
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be();
    });

    it('should have the property splitAction (base name: "split_action")', function() {
      // uncomment below and update the code to test the property splitAction
      //var instance = new OpensvcAgentApi.NodeConfig();
      //expect(instance).to.be();
    });

  });

}));
