/**
 * test opensvc agent api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.12.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestOpensvcAgentApi);
  }
}(this, function(expect, TestOpensvcAgentApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestOpensvcAgentApi.ResourceStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResourceStatus', function() {
    it('should create an instance of ResourceStatus', function() {
      // uncomment below and update the code to test ResourceStatus
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be.a(TestOpensvcAgentApi.ResourceStatus);
    });

    it('should have the property disable (base name: "disable")', function() {
      // uncomment below and update the code to test the property disable
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property encap (base name: "encap")', function() {
      // uncomment below and update the code to test the property encap
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property info (base name: "info")', function() {
      // uncomment below and update the code to test the property info
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property log (base name: "log")', function() {
      // uncomment below and update the code to test the property log
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property monitor (base name: "monitor")', function() {
      // uncomment below and update the code to test the property monitor
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property optional (base name: "optional")', function() {
      // uncomment below and update the code to test the property optional
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property provisioned (base name: "provisioned")', function() {
      // uncomment below and update the code to test the property provisioned
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property restart (base name: "restart")', function() {
      // uncomment below and update the code to test the property restart
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property standby (base name: "standby")', function() {
      // uncomment below and update the code to test the property standby
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property subset (base name: "subset")', function() {
      // uncomment below and update the code to test the property subset
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new TestOpensvcAgentApi.ResourceStatus();
      //expect(instance).to.be();
    });

  });

}));
